### ISSUE TITLE
Tell And Whisper

### ISSUE THREAD

**Issue by beckham894** [takilara/MudletTelegramConnector#2]
Tell and whisper behaves exactly the same

**Comment by EspenSolbu** [comment]
Thanks,
They should not behave exactly the same though, whisper tells the telegram API to not send a notification.
I noticed that for the Windows Desktop app, this does not seem to make a difference, but it makes a difference on my Android Telegram App, in that when i use whisper, the phone remains silent, while when i use tell, the phone plays a notification sound. 

Windows 10 pops up a notification regardless (i did not pay attention to sound though)

**Comment by beckham894** [comment]
It certainly doesn’t work on iOS or Mac version. I have tried both. 

Best Regards,
Nardo

**Comment by EspenSolbu** [comment]
``> It certainly doesn’t work on iOS or Mac version. I have tried both. Best Regards, Nardo``

Both in regards to showing the notification, and playing the notification sound?

Can you check the script file, and check that your version of the script include the different handling of whisper and tell? (maybe i didnt update the package?) (check if the Telegram:Tell command include a true at the end for the whisper handler), see code below for how it looks on my setup.

I'll see if i can find any info in the Telegram API docs regarding this in the meantime.

I actually implemented the feature in the first place, to stop my phone from going ballistic when there are certain events happening on the mud i play, that cause a message storm onto Telegram

```
    elseif sub_cmd=="tell" then
      local msgA = string.split(sub_args," ")
      local username = table.remove(msgA,1)
      local msg = table.concat(msgA," ")
    
      Telegram:Tell(username, msg)
    elseif sub_cmd=="whisper" then
    
      local msgA = string.split(sub_args," ")
      local username = table.remove(msgA,1)
      local msg = table.concat(msgA," ")
    
      Telegram:Tell(username, msg, true)
    end 
```

**Comment by beckham894** [comment]
I set my device mute on sound so I am not very bother with sound

the script are exactly the same as above and the script is working absolutely fine except this function

again great work!

**Comment by beckham894** [comment]
![3CDDF9D3-B6C8-4E3A-BA59-F8645DD8A418](https://user-images.githubusercontent.com/42870100/174654514-e163cc0d-e359-44fb-bf5e-3c82c174a5d0.jpeg)

I have just noticed the little bell button from above. And think there must be a change of setting of the telegram API. 

Which means tell and whisper are both working fine, problem is the telegram API.
