### ISSUE TITLE
Some error in installation instruction

### ISSUE THREAD

**Issue by wiploo** [takilara/MudletTelegramConnector#3]
Hi, thank for you great work. Here's some error in tutorial (in bold):

POINT 4: Go to Mudlet, type #TELEGRAM **TOKEN** <paste_the_token_here>
POINT 7: Try a command like 'look'. **The bot reply telling you: User 'XXXXXXX' not authorized**
POINT 8: In Mudlet you should now see a message about unauthorized user, run the command #TELEGRAM AUTH **XXXXXXX**
POINT 9: In Mudlet, also try '**#TELEGRAM TELL XXXXXXX message**' and it should show up in Telegram

That can help some people easy config the system

**Comment by EspenSolbu** [comment]
Thanks! Ill update the readme!

**Comment by takilara** [comment]
Done
